platform :ios, '8.0'
use_frameworks!

target 'StrivrProject' do
    pod 'Alamofire', '3.5.1'
    pod 'SwiftyJSON', '2.4.0'
end

target 'StrivrProjectTests' do

end

target 'StrivrProjectUITests' do

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
end
